Library/src/Entity/Lectura.php
<?php

namespace App\Entity;

use App\Repository\LecturaRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: LecturaRepository::class)]
class Lectura
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Choice(["Deseado",
            "Interesado",
            "Terminado",
            "Leyendo",
            "Stand-by",                                      
            "Droppeado",])]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $FechaComienzo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $FechaFinal = null;

    #[ORM\OneToOne(inversedBy: 'lectura', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Libro $book = null;

    static $allStatus = [
        "Deseado",
        "Interesado",
        "Terminado",
        "Leyendo",
        "Stand-by",                                      
        "Droppeado",
    ];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getFechaComienzo(): ?\DateTimeInterface
    {
        return $this->FechaComienzo;
    }

    public function setFechaComienzo(?\DateTimeInterface $FechaComienzo): static
    {
        $this->FechaComienzo = $FechaComienzo;

        return $this;
    }

    public function getFechaFinal(): ?\DateTimeInterface
    {
        return $this->FechaFinal;
    }

    public function setFechaFinal(?\DateTimeInterface $FechaFinal): static
    {
        $this->FechaFinal = $FechaFinal;

        return $this;
    }

    public function getBook(): ?Libro
    {
        return $this->book;
    }

    public function setBook(Libro $book): static
    {
        $this->book = $book;

        return $this;
    }
}

Library/src/Entity/Libro.php
<?php

namespace App\Entity;

use App\Repository\LibroRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: LibroRepository::class)]
class Libro
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255)]
    private ?string $Titulo = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max: 255)]
    private ?string $Editorial = null;

    #[ORM\Column(length: 255)]
    private ?string $Autor = null;

    #[ORM\Column(type: Types::BLOB)]
    #[Assert\NotBlank]
    private $Portada = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $FechaPublicacion = null;

    #[ORM\ManyToOne(inversedBy: 'libros')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Language $lengua = null;

    #[ORM\OneToOne(mappedBy: 'book', cascade: ['persist', 'remove'])]
    private ?Lectura $lectura = null;

    public function __construct()
    {
        #$this->lectura = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->Titulo;
    }

    public function setTitulo(string $Titulo): static
    {
        $this->Titulo = $Titulo;

        return $this;
    }

    public function getEditorial(): ?string
    {
        return $this->Editorial;
    }

    public function setEditorial(?string $Editorial): static
    {
        $this->Editorial = $Editorial;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->Autor;
    }

    public function setAutor(string $Autor): static
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function getPortada()
    {
        return $this->Portada;
    }

    public function setPortada($Portada): static
    {
        $this->Portada = $Portada;

        return $this;
    }

    public function getFechaPublicacion(): ?\DateTimeInterface
    {
        return $this->FechaPublicacion;
    }

    public function setFechaPublicacion(\DateTimeInterface $FechaPublicacion): static
    {
        $this->FechaPublicacion = $FechaPublicacion;

        return $this;
    }

    public function getLengua(): ?Language
    {
        return $this->lengua;
    }

    public function setLengua(?Language $lengua): static
    {
        $this->lengua = $lengua;

        return $this;
    }

    public function getLectura(): ?Lectura
    {
        return $this->lectura;
    }

    public function setLectura(Lectura $lectura): static
    {
        // set the owning side of the relation if necessary
        if ($lectura->getBook() !== $this) {
            $lectura->setBook($this);
        }

        $this->lectura = $lectura;

        return $this;
    }

}

Library/src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

use Doctrine\ORM\EntityManagerInterface;

use DateTime;

use App\Repository\LibroRepository;
use App\Repository\LanguageRepository;

use App\Entity\Libro;
use App\Entity\Language;
use App\Entity\Lectura;

class BookController extends AbstractController
{

    private function saveImageTemporalFile($image, $fileName = "temporal"){
        $imagesFolder = $this->getParameter('kernel.project_dir').'/public/image/images/';

        $fileName = $fileName . ".jpg";

        file_put_contents($imagesFolder . $fileName, $image);

        return $fileName;
    }
    
    #[Route('/', name: 'app_index')]
    public function index(LibroRepository $libroRepository, Request $request): Response{
        # Get all books
        $books = $libroRepository->findAllSorted();

        $images = [];

        # Save all book images
        foreach ($books as $book){
            $image = $book->getPortada();
            $book_id = $book->getId();

            $imageFile = $this->saveImageTemporalFile($image, $book_id );
            
            $images[] = $imageFile;
        }

        return $this->render('book/index.html.twig', [
            'controller_name' => 'BookController',
            'books' => $books,
            'images' => $images
        ]);
    }

    #[Route('/book/{bookId}', name: 'app_book')]
    public function book(int $bookId, LibroRepository $libroRepository): Response{
        $book = $libroRepository->find($bookId);
        $status = $book->getLectura();

        # Save book image
        $imageFile = $this->saveImageTemporalFile($book->getPortada());

        return $this->render('book/book.html.twig', [
            'controller_name' => 'BookController',
            'book' => $book,
            'status' => $status,
            'image' => $imageFile
        ]);
    }

    # Create book form
    #[Route('/createBook', methods: ['GET'],  name: 'app_createBook')]
    public function createBook(LanguageRepository $languageRepository): Response{

        $languages = $languageRepository->findAll();

        return $this->render('book/createBook.html.twig', [
            'controller_name' => 'BookController',
            'languages' => $languages
        ]);
    }

    # Create book
    #[Route('/createBook', methods: ['POST'],  name: 'post_createBook')]
    public function post_createBook(Request $request, LanguageRepository $languageRepository, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response{
        $title = $request->request->get('title');
        $author = $request->request->get('author');
        $editorial = $request->request->get('editorial');
        
        $releaseDate = $request->request->get('releaseDate');
        $dateFormat = 'Y-m-d';
        $releaseDate = DateTime::createFromFormat($dateFormat, $releaseDate);

        # Language
        $languageName = $request->request->get('language');
        $language = $languageRepository->findOneBy(['acronym' => $languageName]);
        
        # Front page
        $frontPage = $request->files->get('frontPage')->getContent(); # tmp_name = Path where its stored the image

        $book = new Libro();
        $book->setTitulo($title);
        $book->setAutor($author);
        $book->setEditorial($editorial);
        $book->setFechaPublicacion($releaseDate);

        $book->setLengua($language);

        $book->setPortada($frontPage);

        $lectura = new Lectura();
        $lectura->setStatus("Deseado");
        $book->setLectura($lectura);

        if ( count($bookErrors = $validator->validate($book)) > 0){
            return new Response( (string) $bookErrors );
        }

        $entityManager->persist($book);
        $entityManager->flush();
        
        
        $this->addFlash(
            'success',
            'Book created succesfully'
        );

        return $this->redirectToRoute('app_index');
    }

    #[Route('/updateBook/{bookId}', methods: ['GET'],  name: 'app_updateBook')]
    public function updateBook(int $bookId, LibroRepository $libroRepository, LanguageRepository $languageRepository): Response{
        $book = $libroRepository->find($bookId);

        $imageFile = $this->saveImageTemporalFile($book->getPortada());

        $languages = $languageRepository->findAll();

        return $this->render('book/updateBook.html.twig', [
            'controller_name' => 'BookController',
            'book' => $book,
            'image' => $imageFile,
            'languages' => $languages
        ]);
    }
    
    #[Route('/updateBook/{bookId}', methods: ['POST'],  name: 'post_updateBook')]
    public function post_UpdateBook(int $bookId, Request $request, LibroRepository $libroRepository, LanguageRepository $languageRepository, EntityManagerInterface $entityManager, ValidatorInterface $validator): Response{
        $title = $request->request->get('title');
        $author = $request->request->get('author');
        $editorial = $request->request->get('editorial');
        
        $releaseDate = $request->request->get('releaseDate');
        $dateFormat = 'Y-m-d';
        $releaseDate = DateTime::createFromFormat($dateFormat, $releaseDate);

        # Language
        $languageAcronym = $request->request->get('language');
        $language = $languageRepository->findOneBy(['acronym' => $languageAcronym]);
        
        # Front page
        $frontPage = $request->files->get('frontPage'); # tmp_name = Path where its stored the image

        $book = $libroRepository->find($bookId);
        $book->setTitulo($title);
        $book->setAutor($author);
        $book->setEditorial($editorial);
        $book->setFechaPublicacion($releaseDate);

        $book->setLengua($language);

        if ($frontPage){
            $book->setPortada($frontPage->getContent());
        }

        if ( count($bookErrors = $validator->validate($book)) > 0){
            return new Response( (string) $bookErrors );
        }

        $entityManager->persist($book);
        $entityManager->flush();

        $this->addFlash(
            'success',
            'Book updated succesfully'
        );

        return $this->redirectToRoute('app_book', ["bookId" => $bookId ]);
    }
}

Library/templates/book/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ book.titulo }}{% endblock %}

{% block secondTitle %}
    <div class="estado {{ status.status|lower }}">
        <span id="title"><span class="circulo"></span>{{ book.titulo }}</span>
        <span class="estadoName h5">{{ status.status }}</span>
    </div>
{% endblock %}

{% block content %}
    
    <div class="row media mt-3">
        <div class="col-md-1"></div>
        <div class="col-md-5 col-12 mr-3 text-center">
            <img src="{{ asset('image/images/' ~ image) }}" class="book"/>
        </div>



        <div class="col-12 col-md-5 media-body align-self-center bookDetails">
                    
            <table class="table">
                <tbody>
                    <tr>
                        <td>{{ book.autor }}</td>
                        <td>{{ book.fechaPublicacion|date("d/m/Y") }}</td>
                    </tr>
                            
                    <tr>
                        <td>{{ book.editorial}}</td>
                        <td>{{ book.Lengua.name() }}</td>
                    </tr>

                    <tr>
                        <td colspan="2" class="text-center">
                            {{ (status.fechaComienzo != null) ? status.fechaComienzo|date("d/m/Y") : "??? " }}
                            -
                            {{ (status.fechaFinal != null) ?  status.fechaFinal|date("d/m/Y") : " ???" }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col-md-1"></div>
    </div>

    <div class="row mt-3">
        <div class="col-md-6 col-6 text-center">
            <a href="/updateReadingStatus/{{book.id}}" class="btn btn-primary">Actualizar lectura</a>
        </div>
        <div class="col-md-6 col-6 text-center">
            <a href="/updateBook/{{ book.id }}" class="btn btn-primary">Editar libro</a>
        </div>
    </div>

    
{% endblock %}

Library/templates/book/createBook.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crear libro{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-12 col-md-10 ">

            <div class="col-12">
                <form action="/createBook" method="POST" enctype="multipart/form-data">
                    <div class="form-row">
                        <div class="col-12 col-md-12 form-group">
                            <label for="titleInput">Título</label>
                            <input name="title" type="text" class="form-control" id="titleInput" placeholder="Título del libro" required>
                          </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6 form-group">
                            <label for="authorInput">Autor</label>
                            <input name="author" type="text" class="form-control" id="authorInput" placeholder="Autor del libro" required>
                        </div>
                        <div class="col-12 col-md-6 form-group">
                           <label for="releaseDateInput">Fecha de publicación</label>
                            <input name="releaseDate" type="date" class="form-control" id="releaseDateInput" placeholder="ReleaseDate" required>
                        </div>      
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6 form-group">
                            <label for="editorialInput">Editorial</label>
                            <input name="editorial" type="text" class="form-control" id="editorialInput" placeholder="Editorial" required>
                        </div>
                        <div class="col-12 col-md-6 form-group">
                            <label for="languageInput">Idioma</label>
                            <select name="language" class="form-control" id="languageInput">
                                {% for language in languages %}
                                    <option value="{{ language.acronym }}">{{language.name}}</option>
                                {% endfor %}
                            </select>
                        </div>    
                    </div>
                    <div class="drag-area">    
                        
                            <input name="frontPage" type="file" accept=”.jpg, .jpeg, .png” id="frontPage" required hidden>
                        <div>
                            <span>Portada</span>
                            <div class="row">
                                <div class="col-12">
                                    <span class="header">Drag & Drop</span>
                                    <span class="header">or <span class="button">browse</span></span><br/>
                                    <span class="support">Supports: JPEG, JPG, PNG</span>
                                </div>
                            </div>
                        </div>                  
                        
                    </div>
                    <br/>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
            </div>
                
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}


{% block javascripts %}
    <script src="{{ asset('js/dragImages.js')}}"></script>
{% endblock %}


    

Library/templates/book/createLanguage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update Book {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-12 col-md-10 ">
            <div class="col-1"></div>
            <div class="col-11 col-md-12 ">
                <div id="title" class="h1 title">Crear Idioma</div>
            </div>

            <div class="col-12">
                <form action="/createLanguage" method="POST">
                    <div class="form-row">
                        <div class="col-12 col-md-6 form-group">
                            <label for="languageInput">Idioma</label>
                            <input name="language" type="text" class="form-control" id="languageInput" placeholder="Nombre del Idioma" required>
                        </div>
                        <div class="col-12 col-md-6 form-group">
                           <label for="acronymInput">Acronimo</label>
                            <input name="acronym" type="text" class="form-control" id="acronymInput" placeholder="Acronimo del Idioma" required>
                        </div>      
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
            </div>
                
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}





    

Library/templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book Gallery{% endblock %}

{% block content %}

        <section class="section section-lg bg-default">
        <div class="container">
          <!-- Owl Carousel-->
            <div class="owl-carousel owl-2" data-items="1" data-sm-items="2" data-md-items="3" data-lg-items="4" data-xl-items="5" data-dots="true" data-nav="false" data-stage-padding="0" data-loop="false" data-margin="30" data-mouse-drag="false">
            
                {% if images|length > 0 %}
                    {% for i in 0..(images|length - 1) %}
                        <a class="link-image" href="book/{{ books[i].getId() }}">
                            <img src="{{ asset('image/images/' ~ images[i]) }}" alt="" class="bookGalery" width="228" height="162"/>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
      </section>
{% endblock %}

Library/templates/book/updateBook.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update Book{% endblock %}

{% block secondTitle %}
    Actualizar libro
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-12 col-md-10 ">
            <div class="col-12">
                <div class="text-center">
                    <img src="{{ asset('image/images/' ~ image) }}" id="previewImage" class="bookGalery"/>
                </div>
            </div>

            <div class="col-12">
                <form action="/updateBook/{{ book.id }}" method="POST" enctype="multipart/form-data">
                    <div class="form-row">
                        <div class="col-12 col-md-12 form-group">
                            <label for="titleInput">Titulo</label>
                            <input name="title" type="text" class="form-control" id="titleInput" placeholder="Título del libro" value="{{ book.titulo }}" required>
                          </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6 form-group">
                            <label for="authorInput">Autor</label>
                            <input type="text" name="author" class="form-control" id="authorInput" placeholder="Autor del libro" value="{{ book.autor}}" required>
                        </div>
                        <div class="col-12 col-md-6 form-group">
                           <label for="releaseDateInput">Fecha de publicación</label>
                            <input type="date" name="releaseDate" class="form-control" id="releaseDateInput" placeholder="ReleaseDate" value="{{ book.fechaPublicacion | date('Y-m-d') }}" required>
                        </div>      
                    </div>
                    <div class="form-row">
                        <div class="col-12 col-md-6 form-group">
                            <label for="editorialInput">Editorial</label>
                            <input type="text" name="editorial" class="form-control" id="editorialInput" placeholder="Editorial" value="{{ book.editorial}}" required>
                        </div>
                        <div class="col-12 col-md-6 form-group">
                            <label for="languageInput">Idioma</label>
                            <select name="language" class="form-control" id="languageInput">
                                {% for language in languages %}
                                    <option 
                                        {% if language.name == book.Lengua.name() %}
                                            selected
                                        {% endif %}
                                        
                                        value="{{ language.acronym }}"> {{ language.name}} </option>
                                {% endfor %}
                            </select>
                        </div>    
                    </div>
                    <div class="form-group">
                        <span class="h3">Portada</span>                      
                        <div class="custom-file">
                            <input name="frontPage" type="file" class="custom-file-input" id="frontPage" accept=”.jpg, .jpeg, .png” />
                            <label class="custom-file-label" for="frontPage">Selecciona una nueva portada</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
            </div>
                
        </div>
        <div class="col-md-1"></div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/previewImage.js')}}"></script>
{% endblock %}




    

Library/templates/book/updateReadingStatus.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update Status Reading {% endblock %}

{% block content %}
    
    <div class="row">
        <div class="col-1"></div>
        <div class="col-11 {{ status.status|lower}}">
            <span class="h1">Actualizar lectura</span>
        </div>
    </div>
    <br/>

    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-12 col-md-5 text-center">
            <img src="{{ asset('image/' ~ image) }}" class="book"/>
        </div>
        <div class="col-12 col-md-5">
            <form action="/updateReadingStatus/{{ book.id }}" method="POST" enctype="multipart/form-data">
                <div class="form-row">
                    <div class="col-12 text-center">
                        <a href="/book/{{book.id}}"
                            <span class="h2 titleBookUpdated"> {{ book.titulo }}</span>
                        </a>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-12 col-md-12 form-group">
                        <label for="statusInput">Estado</label>
                        <select class="form-control" id="statusInput" name="status" required>
                            {% for oneStatus in allStatus  %}
                                <option 
                                    {% if (book.Lectura.status() == oneStatus) %}
                                        selected
                                    {% endif %}
                                    value="{{ oneStatus }}">{{ oneStatus }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>    
                </div>
                    
                <div class="form-row">
                    <div class="col-12 col-md-6 form-group">
                        <label for="startDateInput">Fecha de comienzo</label>
                        <input type="date" class="form-control" name="startDate" id="startDateInput" 
                            {% if status.FechaComienzo != null %}
                                value="{{ status.FechaComienzo | date('Y-m-d') }}"
                            {% endif %}
                        >
                    </div>
                    <div class="col-12 col-md-6 form-group">
                        <label for="finishedDateInput">Fecha de finalización</label>
                        <input name="finishDate" type="date" class="form-control" id="finishedDateInput" 
                            {% if status.FechaFinal != null %}
                                value="{{ status.FechaFinal | date('Y-m-d') }}"
                            {% endif %}
                        >
                    </div>      
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}



    